### ISSUE TITLE
Changing header title and button text

### ISSUE THREAD

**Issue by brzi-subasa** [twitterdev/digits-theming-ios#2]
Is it possible to change header text and button text?

**Comment by mikebonnell** [comment]
Currently this isn't supported, but I'm curious - what would like to change the language to?

**Comment by brzi-subasa** [comment]
Yes, I would like to set language based on language of the app, and not based on language of the phone

**Comment by mikebonnell** [comment]
Thanks for letting me know. Currently, the plan is to continue to use the language of the device to localize any text, but I'll share this feedback with the team.

**Comment by mikebonnell** [comment]
Closing issue for now, will re-open if there are additional updates to provide.
