### ISSUE TITLE
Feature request: Ability to change set bar style

### ISSUE THREAD

**Issue by k06a** [twitterdev/digits-theming-ios#5]
I just wanna change status bar style to be able to use black color as background color.

**Comment by andypiper** [comment]
This is just a code sample demonstrating the options for theming Digits on iOS - you may want to join the community discussion on the [developer forums](https://twittercommunity.com) if you would like additional features.

**Comment by k06a** [comment]
Thanks! https://twittercommunity.com/t/feature-request-ability-to-change-ios-status-bar-style/73627
